export default {
  name: "projectStructureAspect",
  type: "object",
  title: "Aspect",
  fields: [
    {
      name: "type",
      type: "string",
      title: "Type",
      options: {
        list: [
          { value: "App", title: "App" },
          { value: "CMS", title: "CMS" },
          { value: "Code", title: "Code" },
          { value: "CRM", title: "CRM" },
          { value: "Database", title: "Database" },
          { value: "Design", title: "Design" },
          { value: "ESP", title: "ESP" },
          { value: "Host", title: "Host" },
          { value: "Code Libraries", title: "Code Libraries" },
          { value: "Testing", title: "Testing" },
          { value: "Tools", title: "Tools" },
        ],
      },
    },
    {
      name: "app",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_app" }] }],
      hidden: ({ parent, value }) => {
        return parent?.type !== "App" && !value;
      },
    },
    {
      name: "cms",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_cms" }] }],
      hidden: ({ parent, value }) => parent?.type !== "CMS" && !value,
    },
    {
      name: "code",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_codeLanguage" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Code" && !value,
    },
    {
      name: "crm",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_crm" }] }],
      hidden: ({ parent, value }) => parent?.type !== "CRM" && !value,
    },
    {
      name: "database",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_database" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Database" && !value,
    },
    {
      name: "design",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_design" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Design" && !value,
    },
    {
      name: "esp",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_esp" }] }],
      hidden: ({ parent, value }) => parent?.type !== "ESP" && !value,
    },
    {
      name: "host",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_host" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Host" && !value,
    },
    {
      name: "codeLibrary",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_codeLibrary" }] }],
      hidden: ({ parent, value }) =>
        parent?.type !== "Code Libraries" && !value,
    },
    {
      name: "testing",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_testing" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Testing" && !value,
    },
    {
      name: "tool",
      type: "array",
      title: "Value",
      layout: "tags",
      of: [{ type: "reference", to: [{ type: "category_generalTool" }] }],
      hidden: ({ parent, value }) => parent?.type !== "Tools" && !value,
    },
  ],
};
